### ISSUE TITLE
Some issues running the code

### ISSUE THREAD

**Issue by trzy** [aelias36/stereo-sew#2]
Hi,

I'm in need of an IK solver for a 7-axis robot I built (the Crane X7, which is open source) and thought this could be a good starting point. However, I'm having difficulty running any of the examples. For instance, running robot_examples/kuka.m produces an error regarding a missing rot() function. 

Did you forget to include some utility code?

Secondly, I'm trying to understand what kinematic family my 7-axis arm belongs to. All of the joints are independent, although a couple are very close together. That is, I think it would be "R-R-R-R-R-R-R" (does this correspond to IK_gen7_dof.m?) but I'm not exactly sure. 

Any help would be appreciated.

Thank you,

-- Bart

**Comment by aelias36** [comment]
Hi Bart,

Thanks for your interest!

The `rot()` function is part of the [ik-geo](https://github.com/rpiRobotics/ik-geo) repo. That's pointed out in the readme but I'll make it even more clear.

Going off the RT website (https://rt-net.jp/products/crane-x7/), it looks like this is a 2R-2R-3R robot. (You can also classify it as a 3R-R-3R robot.) This means the IK can be solved in closed form.

Please let me know once you get everything working so I can close the issue.

-Alex

![img-crane-x7-03-768x386](https://github.com/user-attachments/assets/7674a754-97a1-4068-accb-df837b1b093b)

**Comment by trzy** [comment]
Thanks! I ended up grabbing rot() from somewhere else. I then realized that Octave isn’t going to be able to cut it and will procure a MATLAB trial license. I might need to return to this in a few days.

If I understand correctly there is no way to enforce joint angle range constraints in this package. How would this be handled in such a system? I imagine that the analytical solution could produce solution angles that are beyond the range of some of the joints? Most of the joints have a 180 degree symmetric range but I think that single R elbow joint is less than 90.

This issue can be closed for now (I’ll probably have a few more questions later as I dig in more). Thanks again!

**Comment by aelias36** [comment]
IK for a 2R-2R-3R robot only uses Subproblems 1, 2, and 3, so it should be fairly straightforward to rewrite any code for Octave. IK-Geo also already has implementations in C++, Rust, and Python.

You're correct that right now the solutions returned ignore joint constraints, so it's up to the user to filter out solutions that don't follow the constraints. Also keep in mind the returned joint angles are always in the range $[-\pi, \pi]$, so in some cases it's also up to the user to deal with angle wrapping. This should be fairly simple to implement but I'll be happy to help.
